[package]
name = "pikeru"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.12.1", features = ["image", "tokio", "debug", "advanced", "lazy"] }
num_cpus = "1.16.0"
tokio = { version = "1.37.0", features = ["full"] }
img = { package = "image", version = "0.25.1" }
itertools = "0.12.1"
video-rs = { version = "0.7.3", features = ["ndarray"] }
ndarray = "0.15.6"
