#!/bin/bash
# This script needs a venv in this direcotry. It will try to create one for you if you don't have one.
# set debug=1 if you're having trouble getting it working. It logs to /tmp/pk.log

debug=0

logfile=/tmp/pk.log

# LD_PRELOAD is set by the browser and can interfere with an opencv lib used to display video frames
unset LD_PRELOAD


DIR="$(pwd)"
cd "$(dirname "$(readlink -f "$0")")"

TITLE="File Picker"
MODE="files"
MIME_LIST=""

[ $debug = 1 ] && echo "launcher args: $*" >> $logfile
while getopts "e:t:m:p:i:" opt; do
  case $opt in
    e)
      PARENT="$OPTARG"
      ;;
    t)
      TITLE="$OPTARG"
      ;;
    m)
      MODE="$OPTARG"
      ;;
    p)
      DIR="$OPTARG"
      ;;
    i)
      MIME_LIST="$OPTARG"
      ;;
    \?)
      echo "Invalid option: -$opt $OPTARG" | tee -a $logfile > /dev/stderr
      exit 1
      ;;
  esac
done

if [[ ! "$MODE" =~ ^(file|files|dir|save)$ ]]; then
  echo "Error: Invalid mode flag value (-m). It should be one of [file files dir save]." | tee -a $logfile > /dev/stderr
  exit 1
fi

if [ ! -f "./venv/bin/activate" ]; then
	echo 'No venv found. Creating one now...' > /dev/stderr
	python3 -m venv venv
	. ./venv/bin/activate
	pip3 install -r requirements.txt
else
	. ./venv/bin/activate
fi

cmd="python ./main.py \
	--mode '${MODE}' \
	--path \"${DIR}\" \
	--title '${TITLE}' \
	--mime_list '${MIME_LIST[@]:-}' \
	--parent '${PARENT:-}'" 
[ $debug = 1 ] && echo "cmd: $cmd" >> $logfile
eval "$cmd"
